In [1]:
import numpy as np

import pickle as pickle
import pandas as pd
import pyeeg as pe

In [2]:
channel = [36] #14 Channels chosen to fit Emotiv Epoch+
band = [4,8,12,16,25,45] #5 bands
window_size = 256 #Averaging band power of 2 sec
step_size = 16 #Each 0.125 sec update once
sample_rate = 70 #Sampling rate of 128 Hz
subjectList = ['01','02','03']

In [3]:
from sklearn.preprocessing import normalize


In [4]:
def FFT_Processing (sub, channel, band, window_size, step_size, sample_rate):

    '''
    arguments:  string subject
                list channel indice
                list band
                int window size for FFT
                int step size for FFT
                int sample rate for FFT
    return:     void
    '''
    meta = []
    with open('/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/s' + sub + '.dat', 'rb') as file:

        subject = pickle.load(file, encoding='latin1') #resolve the python 2 data problem by encoding : latin1

        for i in range (0,39):
            # loop over 0-39 trails
            data = subject["data"][i]
            data[36]=(data[36]-min(data[36]))/(max(data[36])-min(data[36]))
            if i==0:
                # data[36]=(data[36]-min(data[36]))/(max(data[36])-min(data[36]))
                print(data[36])
            labels = subject["labels"][i]
            start = 0;

            while start + window_size < data.shape[1]:
                meta_array = []
                meta_data = [] #meta vector for analysis
                for j in channel:
                    X = data[j][start : start + window_size] #Slice raw data over 2 sec, at interval of 0.125 sec
                    Y = pe.bin_power(X, band, sample_rate) #FFT over 2 sec of channel j, in seq of theta, alpha, low beta, high beta, gamma
                    meta_data = meta_data + list(Y[0])

                meta_array.append(np.array(meta_data))
                meta_array.append(labels)

                meta.append(np.array(meta_array))    
                start = start + step_size
                
        meta = np.array(meta)
        np.save('/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/s' + sub, meta, allow_pickle=True, fix_imports=True)

In [5]:
for subjects in subjectList:
    FFT_Processing (subjects, channel, band, window_size, step_size, sample_rate)

[0.24751048 0.24950213 0.24950213 ... 0.18509206 0.18509206 0.18509206]
[0.11221613 0.11221613 0.12468902 ... 0.24946671 0.24322572 0.24322572]
[0.76684949 0.76684949 0.76684949 ... 0.99939557 0.99947112 1.        ]


In [6]:
data= []
label = []
for subjects in subjectList:
  

    with open('/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/s' + subjects + '.npy', 'rb') as file:
        sub = np.load(file,allow_pickle=True)
        for i in range (0,sub.shape[0]):
          data.append(sub[i][0])
          label.append(sub[i][1])
np.save('data', np.array(data), allow_pickle=True, fix_imports=True)
np.save('label', np.array(label), allow_pickle=True, fix_imports=True)

In [7]:
len(data)


57096

In [8]:
len(label)

57096

In [9]:
data[0]

array([2.1734024 , 1.18920276, 0.93530511, 1.54353867, 2.77178679])

In [10]:
l=[[label[i][0]] for i in range(len(label))]

In [11]:
len(l)

57096

In [12]:
l=np.array(l)

In [13]:
len(l)

57096

In [14]:
l[0]

array([7.71])

In [15]:
df=pd.DataFrame(data=data)
df.to_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/data.csv",index=False)

df1=pd.DataFrame(data=l)
df1.to_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/label.csv",index=False)

In [16]:
data1=pd.read_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/data.csv")


In [17]:
data1.head()

0         1         2         3         4
0  2.173402  1.189203  0.935305  1.543539  2.771787
1  2.159191  1.183095  0.936134  1.517083  2.715917
2  2.254652  1.217000  0.959434  1.564887  2.776398
3  2.328341  1.270484  0.990674  1.629562  2.878108
4  2.439677  1.328956  1.046384  1.698458  3.034561

In [18]:
label1=pd.read_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/label.csv")


In [19]:
label1.shape

(57096, 1)

In [20]:
channel = [16] #14 Channels chosen to fit Emotiv Epoch+
band = [4,8,12,16,25,45] #5 bands
window_size = 256 #Averaging band power of 2 sec
step_size = 16 #Each 0.125 sec update once
sample_rate = 70 #Sampling rate of 128 Hz
subjectList = ['1','2','3']

In [21]:
from sklearn.preprocessing import normalize

In [22]:
def FFT_Processing (sub, channel, band, window_size, step_size, sample_rate):
    '''
    arguments:  string subject
                list channel indice
                list band
                int window size for FFT
                int step size for FFT
                int sample rate for FFT
    return:     void
    '''
    meta = []
    for i in sub:
        print("i:",i)
        l=pd.read_csv(f"/home/parameswar/Documents/Anukai solutions/projects/DEAP project/Amigos /data_pre_p/p_{i}/labels_{i}.csv")
        l=np.array(l)
        for j in range (1,21):
            print("vds:",j)
            subject=pd.read_csv(f"/home/parameswar/Documents/Anukai solutions/projects/DEAP project/Amigos /data_pre_p/p_{i}/joined_data_{str(j)}.csv")
            subject=np.array(subject)
            subject=subject.transpose()
            data=subject
            data[16]=(data[16]-min(data[16]))/(max(data[16])-min(data[16]))
            if j==0:
                print(data[16])
            # loop over 0-39 trails
            #data = subject["data"][i]
            labels = l[j-1]
            start = 0;

            while start + window_size < data.shape[1]:
                meta_array = []
                meta_data = [] #meta vector for analysis
                for j in channel:
                    X = data[j][start : start + window_size] #Slice raw data over 2 sec, at interval of 0.125 sec
                    Y = pe.bin_power(X, band, sample_rate) #FFT over 2 sec of channel j, in seq of theta, alpha, low beta, high beta, gamma
                    meta_data = meta_data + list(Y[0])

                meta_array.append(np.array(meta_data))
                meta_array.append(labels)

                meta.append(np.array(meta_array))    
                start = start + step_size
                    
        meta = np.array(meta)
        np.save('/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_amigos/s' + sub, meta, allow_pickle=True, fix_imports=True)

In [23]:
for subjects in subjectList:
    FFT_Processing (subjects, channel, band, window_size, step_size, sample_rate)

i: 1
vds: 1
vds: 2
vds: 3
vds: 4
vds: 5
vds: 6
vds: 7
vds: 8
vds: 9
vds: 10
vds: 11
vds: 12
vds: 13
vds: 14
vds: 15
vds: 16
vds: 17
vds: 18
vds: 19
vds: 20
i: 2
vds: 1
vds: 2
vds: 3
vds: 4
vds: 5
vds: 6
vds: 7
vds: 8
vds: 9
vds: 10
vds: 11
vds: 12
vds: 13
vds: 14
vds: 15
vds: 16
vds: 17
vds: 18
vds: 19
vds: 20
i: 3
vds: 1
vds: 2
vds: 3
vds: 4
vds: 5
vds: 6
vds: 7
vds: 8
vds: 9
vds: 10
vds: 11
vds: 12
vds: 13
vds: 14
vds: 15
vds: 16
vds: 17
vds: 18
vds: 19
vds: 20


In [24]:
data= []
label = []
for subjects in subjectList:
  

    with open('/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_amigos/s' + subjects + '.npy', 'rb') as file:
        sub = np.load(file,allow_pickle=True)
        for i in range (0,sub.shape[0]):
          data.append(sub[i][0])
          label.append(sub[i][1])
np.save('data', np.array(data), allow_pickle=True, fix_imports=True)
np.save('label', np.array(label), allow_pickle=True, fix_imports=True)

In [25]:
len(data)

149844

In [26]:
len(label)

149844

In [27]:
data[0]

array([43.68626285, 24.76042935,  8.33087514, 20.37362737, 31.26121944])

In [28]:
label[0]

array([2.938568, 5.      , 8.235496, 1.      , 1.      , 1.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ])

In [29]:
label[0][1]

5.0

In [30]:
l=[[label[i][1]] for i in range(len(label))]

In [31]:
l=np.array(l)

In [32]:
l.shape

(149844, 1)

In [33]:
df=pd.DataFrame(data=data)
df.to_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_amigos/data.csv",index=False)

df1=pd.DataFrame(data=l)
df1.to_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_amigos/label.csv",index=False)

In [34]:
d_amigos=pd.read_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_amigos/data.csv")
d_deap=pd.read_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/data.csv")

In [35]:
l_amigos=pd.read_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_amigos/label.csv")
l_deap=pd.read_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out_gsr_deap/label.csv")

In [36]:
d_amigos.head()

0          1         2          3          4
0  43.686263  24.760429  8.330875  20.373627  31.261219
1   1.179181   0.646162  0.489928   0.840203   1.471400
2   0.803747   0.446868  0.404655   0.650560   1.028420
3   0.347206   0.208261  0.184850   0.324653   0.399799
4   0.198325   0.116385  0.125306   0.253470   0.186986

In [37]:
d_deap.head()

0         1         2         3         4
0  2.173402  1.189203  0.935305  1.543539  2.771787
1  2.159191  1.183095  0.936134  1.517083  2.715917
2  2.254652  1.217000  0.959434  1.564887  2.776398
3  2.328341  1.270484  0.990674  1.629562  2.878108
4  2.439677  1.328956  1.046384  1.698458  3.034561

In [38]:
l_amigos.head()

0
0  5.0
1  5.0
2  5.0
3  5.0
4  5.0

In [39]:
l_deap.head()

0
0  7.71
1  7.71
2  7.71
3  7.71
4  7.71

In [40]:
type(d_amigos)


pandas.core.frame.DataFrame

In [41]:
frames = [d_deap, d_amigos]

In [42]:
data=pd.concat(frames)

In [43]:
type(data)

pandas.core.frame.DataFrame

In [44]:
data.to_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out/data.csv")

In [45]:
f=[l_deap,l_amigos]

In [46]:
label=pd.concat(f)

In [47]:
type(label)

pandas.core.frame.DataFrame

In [48]:
label.to_csv("/home/parameswar/Documents/Anukai solutions/projects/DEAP project/data_preprocessed_python/out/label.csv")

In [49]:
label


0
0       7.71
1       7.71
2       7.71
3       7.71
4       7.71
5       7.71
6       7.71
7       7.71
8       7.71
9       7.71
10      7.71
11      7.71
12      7.71
13      7.71
14      7.71
15      7.71
16      7.71
17      7.71
18      7.71
19      7.71
20      7.71
21      7.71
22      7.71
23      7.71
24      7.71
25      7.71
26      7.71
27      7.71
28      7.71
29      7.71
...      ...
149814  7.00
149815  7.00
149816  7.00
149817  7.00
149818  7.00
149819  7.00
149820  7.00
149821  7.00
149822  7.00
149823  7.00
149824  7.00
149825  7.00
149826  7.00
149827  7.00
149828  7.00
149829  7.00
149830  7.00
149831  7.00
149832  7.00
149833  7.00
149834  7.00
149835  7.00
149836  7.00
149837  7.00
149838  7.00
149839  7.00
149840  7.00
149841  7.00
149842  7.00
149843  7.00

[206940 rows x 1 columns]